services:
  - type: web
    name: roomify
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
      - key: AI_PROVIDER
        sync: false
      - key: CLOUDFLARE_ACCOUNT_ID
        sync: false
      - key: CLOUDFLARE_API_TOKEN
        sync: false
      - key: CLOUDFLARE_IMAGE_MODEL
        value: "@cf/black-forest-labs/flux-2-klein-4b"
      - key: OPENAI_API_KEY
        sync: false
